version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: PEX
          repo: signavio-circle-ci-corretto
          tag: '11.0.4'
      - aws-ecr/build-and-push-image:
          context: ECR
          repo: circleci-amazon-corretto
          tag: '11.0.4'
