version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Docker login
          command: eval $(aws ecr get-login --region eu-central-1 --no-include-email)

      # build the application image
      - run: 
          name: Build image
          command: docker build -t 695480609797.dkr.ecr.eu-central-1.amazonaws.com/signavio-circle-ci-java:11 .

      # deploy the image
      - run: 
          name: Push to docker hub
          command: docker push 695480609797.dkr.ecr.eu-central-1.amazonaws.com/signavio-circle-ci-java:11
