version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Docker login
          command: eval $(aws ecr get-login --region eu-central-1 --no-include-email)

      # build the application image
      - run:
          name: Build image
          command: docker build -t signavio/circle-ci-java:latest .

      # deploy the image
      - run:
          name: Push to docker hub
          command: docker push signavio/circle-ci-java:latest
